//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Barbeer.BD
{
    using System;
    using System.Collections.Generic;
    
    public partial class Record
    {
        public int Id { get; set; }
        public int ServiceId { get; set; }
        public int BarberId { get; set; }
        public int ClientId { get; set; }
        public System.DateTime DateAndTime { get; set; }
        public string Comment { get; set; }
    
        public virtual Barber Barber { get; set; }
        public virtual Client Client { get; set; }
        public virtual Service Service { get; set; }
    }
}
